import type { SubZone, Scenario, Restaurant } from '../types/restaurant';

export const KWAI_HING_COORDINATES = {
  lat: 22.3636,
  lng: 114.1313,
  zoom: 16,
  radius: 850,
};

export const SUB_ZONES: SubZone[] = [
  {
    id: 'all',
    name: '全部區域',
    nameEn: 'All Zones',
    description: '葵興全區所有食肆精選',
    walkingMinutes: '1-10 分鐘',
    icon: 'Compass',
  },
  {
    id: 'kcc',
    name: 'KCC 九龍貿易中心',
    nameEn: 'Kowloon Commerce Centre',
    description: '甲級商廈、冷氣天橋直達、多國連鎖與特色餐廳',
    walkingMinutes: '步行 2-3 分鐘',
    icon: 'Building2',
  },
  {
    id: 'sun_kwai_hing',
    name: '新葵興廣場',
    nameEn: 'Sun Kwai Hing Plaza',
    description: '港鐵出口直連、巴士總站上蓋、連鎖快餐及酒樓',
    walkingMinutes: '步行 1 分鐘',
    icon: 'Train',
  },
  {
    id: 'kc100_industrial',
    name: 'KC100 & 大連排工廈區',
    nameEn: 'KC100 & Tai Lin Pai Rd',
    description: '隱世工廈Cafe、懷舊飯堂、高質精品咖啡與良心小店',
    walkingMinutes: '步行 5-8 分鐘',
    icon: 'Factory',
  },
  {
    id: 'kwong_fai_circuit',
    name: '光輝圍 / 葵興邨',
    nameEn: 'Kwong Fai Circuit / Estate',
    description: '地道街坊美食街、必食車仔麵、生滾粥與平價宵夜',
    walkingMinutes: '步行 4-6 分鐘',
    icon: 'UtensilsCrossed',
  },
];

export const SCENARIOS: Scenario[] = [
  {
    id: 'quick_bite',
    label: '急急子',
    labelEn: 'Quick Bite',
    emoji: '⚡️',
    description: '趕時間、快買快食、外賣自取極速解決',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
  },
  {
    id: 'rainy_day',
    label: '落雨唔想淋',
    labelEn: 'Rain Shelter',
    emoji: '🌧️',
    description: '商場天橋全程有蓋直達，唔使開遮',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-200',
  },
  {
    id: 'budget',
    label: '平靚正',
    labelEn: 'Budget ($<60)',
    emoji: '💰',
    description: '性價比之王，茶記粉麵 60 蚊有找',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  },
  {
    id: 'chill_cafe',
    label: '慢慢嘆 / 傾偈',
    labelEn: 'Chill Cafe',
    emoji: '☕️',
    description: '環境舒服、好啡、坐耐啲傾偈慢活',
    badgeColor: 'bg-stone-100 text-stone-800 border-stone-200',
  },
  {
    id: 'gathering',
    label: '同事聚餐',
    labelEn: 'Team Lunch',
    emoji: '👥',
    description: '有大枱、酒樓點心、燒肉或放題，啱晒 Team lunch',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-200',
  },
  {
    id: 'healthy',
    label: '健康輕食',
    labelEn: 'Healthy Light',
    emoji: '🥗',
    description: '沙律、Poke、少油低卡、養生清爽',
    badgeColor: 'bg-lime-100 text-lime-800 border-lime-200',
  },
];

export const CUISINES: { id: string; label: string; icon: string }[] = [
  { id: 'hk_cafe', label: '港式茶記/冰室', icon: '🇭🇰' },
  { id: 'japanese_korean', label: '日韓料理', icon: '🍣' },
  { id: 'asian', label: '東南亞風味', icon: '🍜' },
  { id: 'western', label: '西式/Cafe', icon: '☕️' },
  { id: 'noodles_congee', label: '粉麵/粥品', icon: '🥣' },
  { id: 'fast_food', label: '快餐/輕食', icon: '🥪' },
  { id: 'chinese', label: '中菜/點心', icon: '🥟' },
];

export const ZONES = SUB_ZONES;
export const SEARCH_RADIUS_METERS = 1000;
export const WALKING_SPEED_METERS_PER_MIN = 80;

export const SEED_RESTAURANTS: Restaurant[] = [
  // --- KCC (九龍貿易中心) ---
  {
    id: 'kcc-01',
    name: '潮樓 Joyous Gate',
    nameEn: 'Joyous Gate',
    zone: 'kcc',
    zoneName: 'KCC 九龍貿易中心',
    address: '葵涌葵昌路51號九龍貿易中心2樓201號舖',
    addressEn: 'Shop 201, 2/F, Kowloon Commerce Centre, 51 Kwai Cheong Rd',
    lat: 22.3619,
    lng: 114.1332,
    walkingMinutes: 3,
    walkDirections: '葵興站E出口經冷氣行人天橋直達KCC 2樓商場',
    priceLevel: 3,
    rating: 4.1,
    reviewCount: 384,
    cuisine: 'chinese',
    cuisineLabel: '中菜/點心',
    scenarios: ['gathering', 'rainy_day'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '08:00 - 22:00',
    phone: '2487 0138',
    imageUrl: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=800&auto=format&fit=crop&q=80',
    highlights: ['黑金流沙包', '脆皮燒鵝', '午市點心特惠', '大枱多位'],
    description: 'KCC內最受歡迎的商務聚餐酒樓，環境寬敞舒適，點心精緻，落雨天完全唔使淋雨即刻飲茶。',
    googleMapsUrl: 'https://maps.google.com/?q=Joyous+Gate+KCC+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kcc-02',
    name: 'Olive Cafe',
    nameEn: 'Olive Cafe',
    zone: 'kcc',
    zoneName: 'KCC 九龍貿易中心',
    address: '葵涌葵昌路51號九龍貿易中心8樓801號舖',
    addressEn: 'Shop 801, 8/F, Kowloon Commerce Centre, 51 Kwai Cheong Rd',
    lat: 22.3621,
    lng: 114.1333,
    walkingMinutes: 3,
    walkDirections: '葵興站E出口天橋往KCC，乘升降機上8樓',
    priceLevel: 3,
    rating: 4.2,
    reviewCount: 295,
    cuisine: 'western',
    cuisineLabel: '西式/Cafe',
    scenarios: ['chill_cafe', 'rainy_day', 'gathering'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '11:30 - 21:30',
    phone: '2619 1238',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    highlights: ['黑松露意大利飯', '肉眼牛扒套餐', '精美午市意粉', '露天空中平台'],
    description: '隱身在KCC 8樓的優雅西餐廳，具備開揚採光與悠閒氛圍，午市套餐附沙律湯飲，適合跟同事慢慢傾偈或見客。',
    googleMapsUrl: 'https://maps.google.com/?q=Olive+Cafe+KCC+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kcc-03',
    name: '土司工坊 Toast Box',
    nameEn: 'Toast Box',
    zone: 'kcc',
    zoneName: 'KCC 九龍貿易中心',
    address: '葵涌葵昌路51號九龍貿易中心地下G08號舖',
    addressEn: 'Shop G08, G/F, Kowloon Commerce Centre, 51 Kwai Cheong Rd',
    lat: 22.3622,
    lng: 114.1330,
    walkingMinutes: 3,
    walkDirections: '葵興站E出口步行天橋至KCC落地下即達',
    priceLevel: 1,
    rating: 3.9,
    reviewCount: 210,
    cuisine: 'asian',
    cuisineLabel: '東南亞風味',
    scenarios: ['quick_bite', 'rainy_day', 'budget', 'chill_cafe'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '07:30 - 20:30',
    phone: '2418 9033',
    imageUrl: 'https://images.unsplash.com/photo-1594998893017-36147cbcae05?w=800&auto=format&fit=crop&q=80',
    highlights: ['南洋咖椰牛油烤土司', '新加坡叻沙', '香濃熱奶茶', '半熟蛋早餐'],
    description: '正宗南洋風味小館，叻沙湯底濃郁帶微辣椰香，厚牛油咖椰吐司香脆誘人，早餐同下午茶極之抵食。',
    googleMapsUrl: 'https://maps.google.com/?q=Toast+Box+KCC+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kcc-04',
    name: '牛八和牛燒肉屋 Gyuhachi',
    nameEn: 'Gyuhachi Yakiniku',
    zone: 'kcc',
    zoneName: 'KCC 九龍貿易中心',
    address: '葵涌葵昌路51號九龍貿易中心2樓205號舖',
    addressEn: 'Shop 205, 2/F, Kowloon Commerce Centre, 51 Kwai Cheong Rd',
    lat: 22.3620,
    lng: 114.1331,
    walkingMinutes: 3,
    walkDirections: '葵興E出口直經商場天橋入KCC 2樓',
    priceLevel: 3,
    rating: 4.3,
    reviewCount: 312,
    cuisine: 'japanese_korean',
    cuisineLabel: '日韓料理',
    scenarios: ['gathering', 'rainy_day'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '11:30 - 22:00',
    phone: '2420 8928',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    highlights: ['澳洲和牛午市燒肉定食', '角切牛舌', '和牛壽喜燒丼', '抽風良好無油煙'],
    description: '主打高性價比和牛燒肉定食，一人一爐或小組聚餐都好合適，肉質油花分佈均勻，午餐犒賞自己的必選。',
    googleMapsUrl: 'https://maps.google.com/?q=Gyuhachi+Yakiniku+KCC',
    source: 'curated',
  },
  {
    id: 'kcc-05',
    name: 'Pret A Manger',
    nameEn: 'Pret A Manger',
    zone: 'kcc',
    zoneName: 'KCC 九龍貿易中心',
    address: '葵涌葵昌路51號九龍貿易中心地下G01號舖',
    addressEn: 'Shop G01, G/F, Kowloon Commerce Centre, 51 Kwai Cheong Rd',
    lat: 22.3623,
    lng: 114.1328,
    walkingMinutes: 2,
    walkDirections: '葵興E出口行人天橋直通KCC地面入口',
    priceLevel: 2,
    rating: 4.0,
    reviewCount: 164,
    cuisine: 'fast_food',
    cuisineLabel: '快餐/輕食',
    scenarios: ['quick_bite', 'healthy', 'rainy_day', 'chill_cafe'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '07:30 - 19:30',
    phone: '2487 7018',
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&auto=format&fit=crop&q=80',
    highlights: ['有機熱咖啡', '鮮龍蝦小龍蝦三文治', '煙三文魚沙律盒', '法式牛角包'],
    description: '健康上班族首選，主打每日新鮮現做三文治、卷餅與健康沙律，咖啡採用有機咖啡豆，快速外賣完全無壓力。',
    googleMapsUrl: 'https://maps.google.com/?q=Pret+A+Manger+KCC+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kcc-06',
    name: '元氣壽司 Genki Sushi',
    nameEn: 'Genki Sushi',
    zone: 'kcc',
    zoneName: 'KCC 九龍貿易中心',
    address: '葵涌葵昌路51號九龍貿易中心地下G05號舖',
    addressEn: 'Shop G05, G/F, Kowloon Commerce Centre, 51 Kwai Cheong Rd',
    lat: 22.3621,
    lng: 114.1329,
    walkingMinutes: 3,
    walkDirections: '葵興E出口經天橋下至KCC G層',
    priceLevel: 2,
    rating: 4.0,
    reviewCount: 280,
    cuisine: 'japanese_korean',
    cuisineLabel: '日韓料理',
    scenarios: ['quick_bite', 'rainy_day', 'gathering'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '11:00 - 21:30',
    phone: '2487 3622',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop&q=80',
    highlights: ['新幹線列車送餐', '特選刺身拼盤', '炙燒三文魚', '午市壽司烏冬餐'],
    description: '高速列車自動送餐，出品新鮮乾淨，手機點餐落單方便快捷，適合1-4位同事午市快食壽司定食。',
    googleMapsUrl: 'https://maps.google.com/?q=Genki+Sushi+KCC',
    source: 'curated',
  },
  {
    id: 'kcc-07',
    name: '譚仔雲南米線 TamJai Yunnan Mixian',
    nameEn: 'TamJai Yunnan Mixian',
    zone: 'kcc',
    zoneName: 'KCC 九龍貿易中心',
    address: '葵涌葵昌路51號九龍貿易中心地下G03號舖',
    addressEn: 'Shop G03, G/F, Kowloon Commerce Centre, 51 Kwai Cheong Rd',
    lat: 22.3624,
    lng: 114.1331,
    walkingMinutes: 3,
    walkDirections: '葵興站E出口天橋直入KCC地下',
    priceLevel: 1,
    rating: 3.9,
    reviewCount: 420,
    cuisine: 'noodles_congee',
    cuisineLabel: '粉麵/粥品',
    scenarios: ['quick_bite', 'rainy_day', 'budget'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '11:00 - 21:30',
    phone: '2480 3880',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80',
    highlights: ['麻辣五小辣米線', '土匪雞翼', '蒜泥白肉', '竹笙腩肉雙拼'],
    description: '香港打工仔的集體靈魂食堂！麻辣、酸辣湯底過癮醒胃，小食土匪雞翼必叫，落雨天有天橋唔怕濕身。',
    googleMapsUrl: 'https://maps.google.com/?q=TamJai+Yunnan+Mixian+KCC',
    source: 'curated',
  },
  {
    id: 'kcc-08',
    name: '一粥麵 Super Super Congee & Noodle',
    nameEn: 'Super Super Congee & Noodle',
    zone: 'kcc',
    zoneName: 'KCC 九龍貿易中心',
    address: '葵涌葵昌路51號九龍貿易中心地下G06號舖',
    addressEn: 'Shop G06, G/F, Kowloon Commerce Centre, 51 Kwai Cheong Rd',
    lat: 22.3620,
    lng: 114.1330,
    walkingMinutes: 3,
    walkDirections: '葵興站E出口走冷氣天橋直達KCC G層',
    priceLevel: 1,
    rating: 3.8,
    reviewCount: 190,
    cuisine: 'noodles_congee',
    cuisineLabel: '粉麵/粥品',
    scenarios: ['quick_bite', 'rainy_day', 'budget'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '07:00 - 21:00',
    phone: '2428 7388',
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=800&auto=format&fit=crop&q=80',
    highlights: ['生滾滑牛粥', '豉油皇炒麵', '鮮蝦雲吞麵', '脆皮燒肉飯'],
    description: '中式快餐好選擇，粥底綿密香滑，炒麵鑊氣充足，出餐速度極快，想食暖胃中式湯麵的最佳落腳點。',
    googleMapsUrl: 'https://maps.google.com/?q=Super+Super+Congee+KCC',
    source: 'curated',
  },

  // --- 新葵興廣場 (Sun Kwai Hing Plaza) ---
  {
    id: 'skh-01',
    name: '大家樂 Café de Coral',
    nameEn: 'Café de Coral',
    zone: 'sun_kwai_hing',
    zoneName: '新葵興廣場',
    address: '葵涌興芳路166-174號新葵興廣場2樓',
    addressEn: '2/F, Sun Kwai Hing Plaza, 166-174 Hing Fong Rd',
    lat: 22.3634,
    lng: 114.1315,
    walkingMinutes: 1,
    walkDirections: '葵興站A出口直出即入新葵興廣場2樓',
    priceLevel: 1,
    rating: 3.8,
    reviewCount: 350,
    cuisine: 'fast_food',
    cuisineLabel: '快餐/輕食',
    scenarios: ['quick_bite', 'rainy_day', 'budget'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '06:30 - 22:00',
    phone: '2423 3180',
    imageUrl: 'https://images.unsplash.com/photo-1603064752734-4c48eff53d05?w=800&auto=format&fit=crop&q=80',
    highlights: ['一哥焗豬扒飯', '無骨海南雞飯', '西冷牛扒配黑椒汁', '港式熱奶茶'],
    description: '出站1分鐘即到！招牌焗豬扒飯芝士香濃，飯粒金黃，座位充足兼落單快，下雨趕時間的零失誤選擇。',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+de+Coral+Sun+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'skh-02',
    name: '海港酒家 Victoria Harbour Restaurant',
    nameEn: 'Victoria Harbour Restaurant',
    zone: 'sun_kwai_hing',
    zoneName: '新葵興廣場',
    address: '葵涌興芳路166-174號新葵興廣場3樓',
    addressEn: '3/F, Sun Kwai Hing Plaza, 166-174 Hing Fong Rd',
    lat: 22.3635,
    lng: 114.1314,
    walkingMinutes: 1,
    walkDirections: '葵興站A出口經商場扶手電梯直上3樓',
    priceLevel: 3,
    rating: 4.0,
    reviewCount: 460,
    cuisine: 'chinese',
    cuisineLabel: '中菜/點心',
    scenarios: ['gathering', 'rainy_day'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '07:00 - 23:00',
    phone: '2426 8828',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    highlights: ['海港第一包', '蜜汁叉燒皇', '晶瑩鮮蝦餃', '海鮮小菜大宴'],
    description: '葵興站正上方的大型老牌海鮮粵菜酒家，點心水準穩定，大枱充足，極度適合公司部門聚餐與家庭飲茶。',
    googleMapsUrl: 'https://maps.google.com/?q=Victoria+Harbour+Restaurant+Sun+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'skh-03',
    name: '薩莉亞意式餐廳 Saizeriya',
    nameEn: 'Saizeriya',
    zone: 'sun_kwai_hing',
    zoneName: '新葵興廣場',
    address: '葵涌興芳路166-174號新葵興廣場1樓',
    addressEn: '1/F, Sun Kwai Hing Plaza, 166-174 Hing Fong Rd',
    lat: 22.3633,
    lng: 114.1316,
    walkingMinutes: 1,
    walkDirections: '葵興站B出口落1層即達',
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 520,
    cuisine: 'western',
    cuisineLabel: '西式/Cafe',
    scenarios: ['budget', 'rainy_day', 'gathering'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '11:00 - 22:30',
    phone: '2428 1168',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&auto=format&fit=crop&q=80',
    highlights: ['蒜蓉牛油焗田螺', '辣味肉醬多利亞', '意式肉醬意粉', '無限暢飲飲料吧'],
    description: '平民意式之神！30-50蚊就有一份意粉或肉醬飯，價格無敵親民，學生及打工仔的慳錢恩物。',
    googleMapsUrl: 'https://maps.google.com/?q=Saizeriya+Sun+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'skh-04',
    name: '大快活 Fairwood',
    nameEn: 'Fairwood',
    zone: 'sun_kwai_hing',
    zoneName: '新葵興廣場',
    address: '葵涌興芳路166-174號新葵興廣場3樓',
    addressEn: '3/F, Sun Kwai Hing Plaza, 166-174 Hing Fong Rd',
    lat: 22.3636,
    lng: 114.1314,
    walkingMinutes: 1,
    walkDirections: '葵興站A出口直入商場上3樓',
    priceLevel: 1,
    rating: 3.9,
    reviewCount: 310,
    cuisine: 'fast_food',
    cuisineLabel: '快餐/輕食',
    scenarios: ['quick_bite', 'rainy_day', 'budget'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '07:00 - 21:30',
    phone: '2815 6778',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&auto=format&fit=crop&q=80',
    highlights: ['阿活咖喱牛腩飯', '焦糖肉醬肉丸意粉', '無味精老火湯', '粟米肉粒飯'],
    description: '經典阿活咖喱香辣惹味，堅持少鹽少油不加味精，送餐及自助點餐系統順暢，平民午餐首選。',
    googleMapsUrl: 'https://maps.google.com/?q=Fairwood+Sun+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'skh-05',
    name: '美心MX Maxim\'s MX',
    nameEn: "Maxim's MX",
    zone: 'sun_kwai_hing',
    zoneName: '新葵興廣場',
    address: '葵涌興芳路166-174號新葵興商場地下G02號舖',
    addressEn: 'Shop G02, G/F, Sun Kwai Hing Plaza, 166-174 Hing Fong Rd',
    lat: 22.3631,
    lng: 114.1318,
    walkingMinutes: 2,
    walkDirections: '葵興站A出口沿扶手電梯直落地面巴士總站旁',
    priceLevel: 1,
    rating: 3.8,
    reviewCount: 220,
    cuisine: 'fast_food',
    cuisineLabel: '快餐/輕食',
    scenarios: ['quick_bite', 'rainy_day', 'budget'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '07:00 - 21:30',
    phone: '2422 6608',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
    highlights: ['脆皮燒鵝雙拼飯', '去骨海南雞飯', '叉燒滑蛋飯', '下午茶西多士'],
    description: '燒味部師傅刀工利落，脆皮燒鴨與蜜汁叉燒香氣撲鼻，落雨天在商場底層食完直接轉乘巴士極為順路。',
    googleMapsUrl: 'https://maps.google.com/?q=Maxims+MX+Sun+Kwai+Hing',
    source: 'curated',
  },

  // --- KC100 & 大連排工廈區 (Tai Lin Pai Rd Industrial) ---
  {
    id: 'kc-01',
    name: '廚尊 The Project Dignity',
    nameEn: 'The Project Dignity HK',
    zone: 'kc100_industrial',
    zoneName: 'KC100 & 大連排工廈區',
    address: '葵涌大連排道83號KC100 2樓201號舖',
    addressEn: 'Shop 201, 2/F, KC100, 83 Tai Lin Pai Rd',
    lat: 22.3615,
    lng: 114.1345,
    walkingMinutes: 6,
    walkDirections: '葵興站A/E出口沿大連排道步行約5-6分鐘至KC100 2樓',
    priceLevel: 2,
    rating: 4.6,
    reviewCount: 540,
    cuisine: 'asian',
    cuisineLabel: '東南亞風味',
    scenarios: ['chill_cafe', 'gathering', 'healthy'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '08:00 - 18:00',
    phone: '2561 2788',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80',
    highlights: ['新加坡海南雞飯', '正宗星洲叻沙', '手工班蘭戚風蛋糕', '社企共融暖心氛圍'],
    description: '極受好評的新加坡熟食中心概念社企餐廳，由弱勢社群及殘疾人士主理，海南雞嫩滑多汁、叻沙湯頭香濃，極具人情味與社會意義。',
    googleMapsUrl: 'https://maps.google.com/?q=The+Project+Dignity+KC100+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kc-02',
    name: 'BEANS The Greenhouse (荳子)',
    nameEn: 'BEANS',
    zone: 'kc100_industrial',
    zoneName: 'KC100 & 大連排工廈區',
    address: '葵涌大連排道132-140號TLP10一樓 (或鄰近工廈分店)',
    addressEn: '1/F, TLP10, 132-140 Tai Lin Pai Rd',
    lat: 22.3608,
    lng: 114.1352,
    walkingMinutes: 7,
    walkDirections: '葵興站A出口沿大連排道直行約7分鐘',
    priceLevel: 2,
    rating: 4.4,
    reviewCount: 680,
    cuisine: 'western',
    cuisineLabel: '西式/Cafe',
    scenarios: ['chill_cafe', 'gathering', 'healthy'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '11:00 - 21:00',
    phone: '2777 7006',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
    highlights: ['軟殼蟹黑松露意大利粉', '全日早餐 All Day Breakfast', '抹茶提拉米蘇', '手沖精品單品咖啡'],
    description: '知名文青Cafe，綠植工業風裝潢極具設計感，招牌軟殼蟹意粉份量十足，咖啡香醇，是葵興打工仔逃離壓力的慢活秘密基地。',
    googleMapsUrl: 'https://maps.google.com/?q=BEANS+Tai+Lin+Pai+Road',
    source: 'curated',
  },
  {
    id: 'kc-03',
    name: 'Coffeelin KC100',
    nameEn: 'Coffeelin',
    zone: 'kc100_industrial',
    zoneName: 'KC100 & 大連排工廈區',
    address: '葵涌大連排道83號KC100地下G04號舖',
    addressEn: 'Shop G04, G/F, KC100, 83 Tai Lin Pai Rd',
    lat: 22.3616,
    lng: 114.1343,
    walkingMinutes: 5,
    walkDirections: '葵興站A出口行經大連排道至KC100地下大堂',
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 230,
    cuisine: 'western',
    cuisineLabel: '西式/Cafe',
    scenarios: ['chill_cafe', 'quick_bite'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '08:00 - 18:00',
    phone: '2428 3828',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    highlights: ['米蘭直送咖啡豆', '意式Espresso Tonic', 'Gelato意式雪糕', '牛油果酸種麵包'],
    description: '正宗米蘭風情精品咖啡店，選用米蘭老牌烤豆，香氣醇厚，店面環境安靜高級，適合帶電腦工作或跟拍檔傾專案。',
    googleMapsUrl: 'https://maps.google.com/?q=Coffeelin+KC100+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kc-04',
    name: '新大佛口食坊 (工廈大排檔小菜)',
    nameEn: 'Sun Tai Fat Hau Restaurant',
    zone: 'kc100_industrial',
    zoneName: 'KC100 & 大連排工廈區',
    address: '葵涌大連排道144-152號金豐工業大廈地下',
    addressEn: 'G/F, Kim Fung Ind Bldg, 144-152 Tai Lin Pai Rd',
    lat: 22.3602,
    lng: 114.1356,
    walkingMinutes: 8,
    walkDirections: '葵興站A出口經大連排道步行約8分鐘至金豐工廈',
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 410,
    cuisine: 'hk_cafe',
    cuisineLabel: '港式茶記/冰室',
    scenarios: ['budget', 'quick_bite', 'gathering'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '07:00 - 17:30',
    phone: '2420 5688',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop&q=80',
    highlights: ['熱辣辣黑椒鐵板牛肉飯', '生炒牛肉飯', '乾炒牛河鑊氣十足', '工廈特大份量午餐'],
    description: '大連排道老字號工廈飯堂！廚房鑊氣震天，炒粉麵飯份量巨大，價錢平過出面兩成，工友同辦公室男同事的飽肚聖地。',
    googleMapsUrl: 'https://maps.google.com/?q=Sun+Tai+Fat+Hau+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kc-05',
    name: '華星冰室 Chrisly Cafe',
    nameEn: 'Chrisly Cafe',
    zone: 'kc100_industrial',
    zoneName: 'KC100 & 大連排工廈區',
    address: '葵涌大連排道162-170號金龍工業中心地下',
    addressEn: 'G/F, Golden Dragon Ind Ctr, 162-170 Tai Lin Pai Rd',
    lat: 22.3598,
    lng: 114.1359,
    walkingMinutes: 8,
    walkDirections: '葵興站A出口行至大連排道中段金龍工中',
    priceLevel: 1,
    rating: 4.0,
    reviewCount: 390,
    cuisine: 'hk_cafe',
    cuisineLabel: '港式茶記/冰室',
    scenarios: ['quick_bite', 'budget'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '07:00 - 18:00',
    phone: '2428 8868',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&auto=format&fit=crop&q=80',
    highlights: ['黑松露炒蛋多士', '北海道特選3.6牛乳炒蛋', '香濃熱奶茶', '校長多士'],
    description: '以嫩滑香濃炒蛋聞名的香港傳奇冰室，用北海道3.6牛乳炒製的滑蛋層層疊疊，烘底厚多士牛油香四溢。',
    googleMapsUrl: 'https://maps.google.com/?q=Chrisly+Cafe+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kc-06',
    name: '聯發茶餐廳 (大連排道經典老店)',
    nameEn: 'Luen Fat Restaurant',
    zone: 'kc100_industrial',
    zoneName: 'KC100 & 大連排工廈區',
    address: '葵涌大連排道182-190號金豐工業大廈二期地下',
    addressEn: 'G/F, Phase 2, 182-190 Tai Lin Pai Rd',
    lat: 22.3592,
    lng: 114.1362,
    walkingMinutes: 9,
    walkDirections: '沿大連排道直行約9分鐘',
    priceLevel: 1,
    rating: 4.1,
    reviewCount: 180,
    cuisine: 'hk_cafe',
    cuisineLabel: '港式茶記/冰室',
    scenarios: ['budget', 'quick_bite'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '06:30 - 17:00',
    phone: '2425 2128',
    imageUrl: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&auto=format&fit=crop&q=80',
    highlights: ['沙爹牛肉公仔麵', '脆皮熱狗王', '手打鹹檸七', '炭燒豬扒包'],
    description: '充滿人情味與昔日工業黃金時代色彩的茶記，沙爹汁濃郁微甜，牛肉滑溜，是不少老街坊同工廈員工的每日固定早餐。',
    googleMapsUrl: 'https://maps.google.com/?q=Luen+Fat+Restaurant+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kc-07',
    name: 'Poke Go 葵興夏威夷蓋飯',
    nameEn: 'Poke Go',
    zone: 'kc100_industrial',
    zoneName: 'KC100 & 大連排工廈區',
    address: '葵涌葵昌路72-76號Life@KCC (近大連排工廈側)',
    addressEn: 'Life@KCC, 72-76 Kwai Cheong Rd',
    lat: 22.3627,
    lng: 114.1336,
    walkingMinutes: 4,
    walkDirections: '葵興E出口直經天橋至Life@KCC',
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 215,
    cuisine: 'fast_food',
    cuisineLabel: '快餐/輕食',
    scenarios: ['healthy', 'quick_bite', 'rainy_day'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '11:30 - 20:30',
    phone: '2619 8838',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80',
    highlights: ['新鮮吞拿魚三文魚雙拼', '慢煮雞胸藜麥沙律', '山葵蛋黃醬', '牛油果毛豆仁'],
    description: '夏威夷生魚飯Poke Bowl，健康低卡高蛋白，可自由配搭紫米、沙律菜或十穀米，注重身型與健康管理必試。',
    googleMapsUrl: 'https://maps.google.com/?q=Poke+Go+Life+KCC',
    source: 'curated',
  },

  // --- 光輝圍 / 葵興邨 (Kwong Fai Circuit / Kwai Hing Estate) ---
  {
    id: 'kfc-01',
    name: '友和車仔麵 (光輝圍馳名老字號)',
    nameEn: 'Yau Wo Cart Noodles',
    zone: 'kwong_fai_circuit',
    zoneName: '光輝圍 / 葵興邨',
    address: '葵涌光輝圍27號昌發大廈地下',
    addressEn: 'G/F, Cheong Fat Bldg, 27 Kwong Fai Circuit',
    lat: 22.3649,
    lng: 114.1302,
    walkingMinutes: 5,
    walkDirections: '葵興站A出口穿過光輝圍行人隧道直行即到',
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 890,
    cuisine: 'noodles_congee',
    cuisineLabel: '粉麵/粥品',
    scenarios: ['budget', 'quick_bite'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '10:30 - 23:00',
    phone: '2422 1388',
    imageUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&auto=format&fit=crop&q=80',
    highlights: ['招牌秘製咖喱魷魚', '入味蘿蔔', '滷水大腸', '辣汁陳皮魚蛋'],
    description: '光輝圍無人不知的車仔麵傳奇！配料超過50款任揀，咖喱汁同秘製辣汁辣得過癮，蘿蔔清甜無筋，幾十蚊食到捧住個肚走。',
    googleMapsUrl: 'https://maps.google.com/?q=Yau+Wo+Cart+Noodles+Kwong+Fai+Circuit',
    source: 'curated',
  },
  {
    id: 'kfc-02',
    name: '光輝圍生滾粥品麵家',
    nameEn: 'Kwong Fai Congee & Noodles',
    zone: 'kwong_fai_circuit',
    zoneName: '光輝圍 / 葵興邨',
    address: '葵涌光輝圍17號地下',
    addressEn: 'G/F, 17 Kwong Fai Circuit',
    lat: 22.3651,
    lng: 114.1300,
    walkingMinutes: 5,
    walkDirections: '葵興站A出口經光輝圍地下街口直入',
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 310,
    cuisine: 'noodles_congee',
    cuisineLabel: '粉麵/粥品',
    scenarios: ['budget', 'quick_bite'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '06:30 - 21:00',
    phone: '2420 7712',
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=800&auto=format&fit=crop&q=80',
    highlights: ['生滾及第粥', '鮮鯇魚片粥', '即炸酥脆油炸鬼', '鮮蝦布拉腸粉'],
    description: '真材實料街坊老店，生滾魚片鮮甜彈牙，粥底綿滑回甘，新鮮炸出油條金黃酥脆，早餐或下午茶暖胃首選。',
    googleMapsUrl: 'https://maps.google.com/?q=Kwong+Fai+Congee+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kfc-03',
    name: '雲貴川風味米線',
    nameEn: 'Yunnan & Guizhou Rice Noodles',
    zone: 'kwong_fai_circuit',
    zoneName: '光輝圍 / 葵興邨',
    address: '葵涌光輝圍33號地下',
    addressEn: 'G/F, 33 Kwong Fai Circuit',
    lat: 22.3648,
    lng: 114.1305,
    walkingMinutes: 5,
    walkDirections: '葵興A出口直入光輝圍食街',
    priceLevel: 1,
    rating: 4.3,
    reviewCount: 560,
    cuisine: 'noodles_congee',
    cuisineLabel: '粉麵/粥品',
    scenarios: ['budget', 'quick_bite'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '11:00 - 22:00',
    phone: '2489 9122',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80',
    highlights: ['特濃酸辣小鍋米線', '滷水豬頸肉', '秘製酸菜', '香酥炸醬'],
    description: '光輝圍酸辣米線代表！湯底酸香濃烈辣勁十足，炸醬炒得香噴噴，配搭吸汁豆卜同生菜，嗜辣一族食過返尋味。',
    googleMapsUrl: 'https://maps.google.com/?q=Yunnan+Guizhou+Rice+Noodles+Kwong+Fai+Circuit',
    source: 'curated',
  },
  {
    id: 'kfc-04',
    name: '潮發黑腩潮州粉麵',
    nameEn: 'Chiu Fat Chiu Chow Noodles',
    zone: 'kwong_fai_circuit',
    zoneName: '光輝圍 / 葵興邨',
    address: '葵涌光輝圍8號地下',
    addressEn: 'G/F, 8 Kwong Fai Circuit',
    lat: 22.3653,
    lng: 114.1298,
    walkingMinutes: 6,
    walkDirections: '葵興站A出口經禾塘咀街轉入光輝圍',
    priceLevel: 1,
    rating: 4.4,
    reviewCount: 470,
    cuisine: 'noodles_congee',
    cuisineLabel: '粉麵/粥品',
    scenarios: ['budget', 'quick_bite'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '08:00 - 20:30',
    phone: '2429 8831',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&auto=format&fit=crop&q=80',
    highlights: ['清湯招牌崩沙腩', '潮州手打魚蛋', '炸魚皮', '牛筋牛肚雙拼河'],
    description: '葵涌區首屈一指的牛腩粉麵！崩沙腩肉香肉汁四溢，牛筋炆得膠質軟糯，湯底清甜無味精，辣椒油香醇無比。',
    googleMapsUrl: 'https://maps.google.com/?q=Chiu+Fat+Beef+Brisket+Noodles+Kwai+Hing',
    source: 'curated',
  },
  {
    id: 'kfc-05',
    name: '嘉寶漢堡 Kabo Burger',
    nameEn: 'Kabo Burger',
    zone: 'kwong_fai_circuit',
    zoneName: '光輝圍 / 葵興邨',
    address: '葵涌青山公路葵涌段499號嘉寶大廈地下 (光輝圍路口)',
    addressEn: 'G/F, Kabo Bldg, 499 Castle Peak Rd, Kwai Chung',
    lat: 22.3658,
    lng: 114.1309,
    walkingMinutes: 6,
    walkDirections: '葵興站A出口往青山公路方向步行約6分鐘',
    priceLevel: 2,
    rating: 4.5,
    reviewCount: 1120,
    cuisine: 'western',
    cuisineLabel: '西式/Cafe',
    scenarios: ['quick_bite', 'chill_cafe'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '12:00 - 21:00',
    phone: '9521 4414',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    highlights: ['黑松露手打牛肉堡', '日式芥末牛堡', '蜜糖芥末薯角', '即烤鬆軟牛油麵包'],
    description: '從葵涌發跡揚名全港的手工漢堡神店！厚切牛肉漢堡肉汁噴發，生菜番茄清爽解膩，價錢平過外國名店一大截，必食！',
    googleMapsUrl: 'https://maps.google.com/?q=Kabo+Burger+Kwai+Chung',
    source: 'curated',
  },
  {
    id: 'kfc-06',
    name: '天皇甜品 (光輝圍老字號糖水店)',
    nameEn: 'Tin Wong Dessert',
    zone: 'kwong_fai_circuit',
    zoneName: '光輝圍 / 葵興邨',
    address: '葵涌光輝圍41號地下',
    addressEn: 'G/F, 41 Kwong Fai Circuit',
    lat: 22.3646,
    lng: 114.1307,
    walkingMinutes: 5,
    walkDirections: '葵興站A出口步行至光輝圍尾段',
    priceLevel: 1,
    rating: 4.2,
    reviewCount: 380,
    cuisine: 'fast_food',
    cuisineLabel: '快餐/輕食',
    scenarios: ['chill_cafe', 'budget'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '14:00 - 01:00',
    phone: '2422 6128',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=80',
    highlights: ['楊枝甘露', '薑汁黑糖湯圓', '香滑芝麻糊', '芒果小丸子豆腐花'],
    description: '葵興街坊最愛的傳統中西糖水店，午後開到凌晨一點，楊枝甘露芒果肉厚芒汁濃郁，熱薑汁湯圓驅寒暖胃。',
    googleMapsUrl: 'https://maps.google.com/?q=Tin+Wong+Dessert+Kwong+Fai+Circuit',
    source: 'curated',
  },
  {
    id: 'kfc-07',
    name: '葵興街市熟食中心 (地道街坊兩餸飯及點心)',
    nameEn: 'Kwai Hing Cooked Food Centre',
    zone: 'kwong_fai_circuit',
    zoneName: '光輝圍 / 葵興邨',
    address: '葵涌葵興路100號葵興邨街市2樓',
    addressEn: '2/F, Kwai Hing Market, 100 Kwai Hing Rd',
    lat: 22.3640,
    lng: 114.1293,
    walkingMinutes: 4,
    walkDirections: '葵興站C出口沿葵興路直行4分鐘上街市熟食中心',
    priceLevel: 1,
    rating: 4.0,
    reviewCount: 290,
    cuisine: 'hk_cafe',
    cuisineLabel: '港式茶記/冰室',
    scenarios: ['budget', 'quick_bite'],
    isSheltered: true,
    isOpenNow: true,
    openingHoursText: '06:00 - 16:00',
    phone: '2422 8390',
    imageUrl: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=800&auto=format&fit=crop&q=80',
    highlights: ['鑊氣雙拼兩餸飯 ($38)', '熱辣蒸點心籠', '椒鹽豬扒飯', '港式濃茶'],
    description: '最接地氣的平民食堂！兩餸飯只要38蚊餸料堆到盒滿，鑊氣小炒即叫即整，還有熱氣騰騰的傳統蒸籠點心。',
    googleMapsUrl: 'https://maps.google.com/?q=Kwai+Hing+Market+Cooked+Food+Centre',
    source: 'curated',
  },
  {
    id: 'kfc-08',
    name: '金記冰室 Kam Kee Cafe',
    nameEn: 'Kam Kee Cafe',
    zone: 'kwong_fai_circuit',
    zoneName: '光輝圍 / 葵興邨',
    address: '葵涌禾塘咀街87號地下',
    addressEn: 'G/F, 87 Wo Tong Tsui St',
    lat: 22.3643,
    lng: 114.1306,
    walkingMinutes: 4,
    walkDirections: '葵興站A出口往光輝圍交界處步行4分鐘',
    priceLevel: 1,
    rating: 3.9,
    reviewCount: 260,
    cuisine: 'hk_cafe',
    cuisineLabel: '港式茶記/冰室',
    scenarios: ['quick_bite', 'budget'],
    isSheltered: false,
    isOpenNow: true,
    openingHoursText: '07:00 - 21:00',
    phone: '2428 5590',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    highlights: ['經典黑牛雪糕特飲', '金牌乾炒牛河', '流心蛋菠蘿包', '自製沙爹牛肉麵'],
    description: '懷舊復古綠白格仔地磚裝潢，傳統茶記經典滋味，菠蘿包外脆內軟夾著厚牛油，下午茶時段性價比極高。',
    googleMapsUrl: 'https://maps.google.com/?q=Kam+Kee+Cafe+Wo+Tong+Tsui+Street',
    source: 'curated',
  },
];

export const kwaiHingSeedPlaces = SEED_RESTAURANTS;

